---
title: "Events"
---

This page lists all upcoming ML4GEO events. Please bear in mind that the MS Teams Channel will remain the place to receive the most up-to-date information about ML4GEO activities.

<!-- -------------------------------------------------------------------------

# 04/05/2026 - ML4GEO Seminar: Becky Wilks

Join us for our bi-weekly ML4GEO meet-up.

A relaxed, friendly space to chat about all things Machine Learning for Geoscience and Earth Observation.

In our upcoming seminar, we will hear from Becky Wilks. 

**Title**: Counting Animals and Objects More Efficiently with Machine Learning

**🕓When**: Monday 4th May, 4-5pm

**📍Where**: TBC -->

<!-- -------------------------------------------------------------------------

# 20/04/2026 - ML4GEO Seminar: Lauren Young

Join us for our bi-weekly ML4GEO meet-up.

A relaxed, friendly space to chat about all things Machine Learning for Geoscience and Earth Observation.

In our upcoming seminar, we will hear from Lauren Young. 

**Title**: Automating complex segmentation of the brain for Alzheimers Research

**🕓When**: Monday 20th April, 4-5pm

**📍Where**: 2.05 Ogilvie, Drummond Street Campus, Central (or online). -->

-------------------------------------------------------------------------

# <del>23/03/2026 - ML4GEO Seminar: Holly Houliston</del>

Join us for our bi-weekly ML4GEO meet-up.

A relaxed, friendly space to chat about all things Machine Learning for Geoscience and Earth Observation.

In our upcoming seminar, we will hear from Holly Houliston at the British Antarctic Survey. 

**Title**: AI 4 Wildlife: Diffusion for Synthetic Data Creation and Explainable AI

**🕓When**: Monday 23rd March, 4-5pm

**📍Where**: 2.05 Ogilvie, Drummond Street Campus, Central (or online).

-------------------------------------------------------------------------

# <del>19/03/2026 - Tutorial: Agentic AI</del>

Join us for a tutorial on agentic AI with **Dr Jon Minton** from the School of Social and Political Science.

📖 Overview:
Jon Minton is a senior statistician with a broad background covering data science, public health, health economics, social policy, urban studies, demography and software development. He believes that agentic AI solutions like Claude Code have transformative potential throughout other domains of analytical knowledge work too, including for academic research. Before launching into a coding demo Jon will talk through some of the important concepts to think about when it comes to agentic AI compared with AI through a standard chatbot interface. For agentic AI considerations will cover:  
* Agent, prompt, I/O (chat window)
* Environment/Context
* Workspace
* State/History, and SOPs/architecture
* Tooling
* Version control.

**🕓When**: Thursday 19th March, 12:00 - 1:00 PM

**📍Where**: 1.1 Lister Learning and Teaching Centre, 5 Roxburgh Pl, Edinburgh EH8 9SU [1 min walk from Drummond] 

**Accessibility**:  Online access will be possible via Teams meeting in ML4GEO calendar invite. Recordings will also be made available. 

-------------------------------------------------------------------------

# <del>23/02/2026 - ML4GEO Seminar: Lorena Benitez</del>

Come join us next Monday for a talk by 4th year PhD student **Lorena Benitez** on Using Uniform Manifold Approximation and Projection (UMAP) to Reduce Ecological Complexity. UMAP is a dimension reduction method (think PCA type tool) that is both computationally efficient and powerful.
 

**Title**: Using Uniform Manifold Approximation and Projection (UMAP) to Reduce Ecological Complexity

 
**Abstract**: *"For my PhD, I am mapping tree communities across southern Africa using vegetation plots and satellite remote sensing. When traditional ecological methods for defining tree communities from plot data failed, I had to look for other techniques for reducing the complexity of my data into something that is easily mappable*. This led me to Uniform Manifold Approximation and Projection (UMAP). In this talk, I will give an overview of UMAP, compare it to other similar techniques, discuss clustering methods and parameter selection, and share my personal experiences using UMAP in R and Python."*

 

For more information about UMAP, check out this [website](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fumap-learn.readthedocs.io%2Fen%2Flatest%2F&data=05%7C02%7C%7C67ef89bdf014462eb86408de6ede1410%7C2e9f06b016694589878910a06934dc61%7C0%7C0%7C639070097301772280%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=k1lE3dul0KkfDmdC9L7hrsuTlhUbsXFsblcyzQnPzO8%3D&reserved=0)."


**🕓When**: Monday 23rd February, 4-5pm

**📍Where**: 2.05 Ogilvie, Drummond Street Campus, Central (or online).

-------------------------------------------------------------------------



# <del>09/02/2026 - ML4GEO Seminar: Dr Niall Rodgers</del>

Join us for our bi-weekly ML4GEO meet-up

A relaxed, friendly space to chat about all things Machine Learning for Geoscience and Earth Observation. 
 
In our next session we are excited to welcome a seminar from **Dr Niall Rodgers** from the School of Physics and Astronomy:
 
**Title**: Complexity Begets Simplicity: Self-Supervised Learning for Palaeontological Images with Few or No Labels
 
**Abstract**:  Palaeontology has seen widespread and growing use of machine learning to classify and analyse large datasets of fossils. However, palaeontology is a challenging field in which to apply machine learning. Datasets may be small or unlabelled, images may be complex and different from standard datasets and palaeontologists may lack specialist training and access to necessary computational resources. We show how these challenges can be addressed by utilising recent developments in self-supervised learning (SSL). Using a frozen DINOv3 feature extractor and a simple linear classifier, with reduced data, we can achieve comparable results to literature benchmarks using Convolutional Neural Networks (CNNs), the previous standard, when classifying fossil tracks, pollen, radiolaria, foraminifera and a dataset of diverse fossil images. Additionally, the rich feature vectors generated by the model can be used for few-shot learning, unsupervised clustering and quantification of disparity. Using state-of-the-art self-supervised methods increases accessibility by reducing code, compute and data required. It also maintains accuracy, while increasing reproducibility by reducing parameters and allowing simple future-proof model agnostic pipelines which may become the new standard approach in palaeontology, https://www.biorxiv.org/content/10.1101/2025.11.13.688022v1
 
**🕓When**: Monday 9th February, 4-5pm

**📍Where**: G.31 Murchison House, Kings Campus
 


-------------------------------------------------------------------------

# <del>**22/07/2025 - Geospatial Foundation Models Ideathon/Hackathon**</del>

ML4GEO is a research group passionate about connecting geospatial sciences with machine learning! 

This month, we're excited to host our inaugural Ideathon/Hackathon focused on Geospatial Foundation Models! Join us at ML4GEO for a 2-day event on July 22-23 at the Edinburgh Futures Institute. where we'll collaborate to generate ideas and explore use cases together. No technical expertise required!

Geospatial Foundation models (GFMs) are revolutionising geospatial machine learning (TerraMind, SSL4EO-S12 , Google Embeddings,… ) with state-of-the-art performance and generalizability across sensors/regions and benchmark spatial imaging tasks. 

Our Ideathon/Hackathon aims to:
* Provide a brief introduction to GFMs.
* Offer space for discussion and idea generation for applications.
* Facilitate group work to develop prototypes and implement ideas using actual GFMs and FM embeddings. 

You'll have the opportunity to identify your own problem and choose which GFM and data to use, facilitating a self-driven learning experience!

Sign-ups [here](https://forms.office.com/e/tT82ywNzin)!



<!-- Please head over to the [GitHub repo](https://github.com/ml4geo-ed/hackathon-2025) for more details -->